# Generated by Django 6.0.4 on 2026-04-27 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('telephone', models.IntegerField(unique=True)),
                ('adresse', models.CharField(max_length=200)),
                ('numero_compteur', models.CharField(max_length=20)),
                ('type_adonnement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(max_length=20)),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(max_length=50)),
                ('abonne_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEmanager.abonne', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('facture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEmanager.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Releve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=10)),
                ('consommation', models.FloatField(max_length=20)),
                ('date_releve', models.DateField(default=django.utils.timezone.now)),
                ('abonne_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEmanager.abonne', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='releve_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEmanager.releve', unique=True),
        ),
    ]
