# Generated by Django 6.0.4 on 2026-04-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonne',
            old_name='type_adonnement',
            new_name='type_abonne',
        ),
    ]
