# Generated by Django 6.0.4 on 2026-04-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEmanager', '0002_rename_type_adonnement_abonne_type_abonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='releve_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEmanager.releve', unique=True),
        ),
    ]
