# Generated by Django 6.0.4 on 2026-04-29 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEmanager', '0003_alter_facture_releve_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='abonne_id',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='releve_id',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='facture_id',
        ),
        migrations.RemoveField(
            model_name='releve',
            name='abonne_id',
        ),
        migrations.AddField(
            model_name='facture',
            name='abonne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEmanager.abonne'),
        ),
        migrations.AddField(
            model_name='facture',
            name='releve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEmanager.releve'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEmanager.facture'),
        ),
        migrations.AddField(
            model_name='releve',
            name='abonne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEmanager.abonne'),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='numero_compteur',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='releve',
            name='consommation',
            field=models.FloatField(),
        ),
    ]
